name: huggingface_chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit==1.22.0
    - huggingface-hub==0.13.0
    - langchain==0.0.150
    - transformers==4.28.1
    - protobuf==3.20.0
    - pydantic==1.10.2 