name: huggingface_chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit==1.22.0
    - requests==2.28.2
    - python-dotenv==1.0.0
    - markdown==3.4.3 